export class Candidate {
    candidateId!:number;
    candidateName:String="";
    age!:number;
    totalExperiance!:number;
    relevantExperiance!:number;
    expectedLwd:String="";
    location:String="";
    skills:String="";
    technology:String="";
    maritialStatus:String="";
    status:String="Shortlist";
    gcm!:String;
    position!:String;
    timestamp!:string; 
    duedate!:String;
    project!:String;
    constructor(){}
}
